language: generic
sudo: required
services:
  - docker
  
before_install:
  - docker build -t bcsalton/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true bcsalton/react-test npm test
  
after_success:
  - docker build -t bcsalton/multi-client ./client
  - docker build -t bcsalton/multi-nginx ./nginx
  - docker build -t bcsalton/multi-server ./server
  - docker build -t bcsalton/multi-worker ./worker